### ISSUE TITLE
patchValue for form builder with file picker

### ISSUE THREAD

**Issue by pragatisha** [flutter-form-builder-ecosystem/form_builder_file_picker#26]
Tried to patch initial value to form builder. every other form fields pick the initial value but not file picker. How can I solve that ?

**Comment by deandreamatias** [comment]
Hi!
Can provide this thinks please?

## Environment

**Package version:**  

<details>
  <summary>Flutter doctor</summary>


```
```

</details>

<details>
  <summary>Code sample</summary>



```dart
```

</details>

## Description

**Expected behavior:**

**Current behavior:**

## Steps to reproduce

1. This
2. Than that
3. Then
